logging:
  level:
    root: INFO

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
  flyway:
    locations: classpath:db/migration,classpath:db/seed

app:
  cors:
    allowed-origins: "https://secureshop-frontend-staging.onrender.com"
