server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
      cors:
        allowed-origins: "${app.cors.allowed-origins}"
        allowed-methods: GET
  endpoint:
    health:
      show-details: always

app:
  cors:
    allowed-origins: "http://localhost:5173"
